// BULK_PLAN.js

window.BULK_PLAN = {
  "tables": {
    "BULK_PLAN": {
      "columns": {
        "BULK_PLAN_GID": {
          "type": "VARCHAR2(101)",
          "nullable": false,
          "key_value": true,
          "info": "Global identifier generated for each call to the bulk plan process. "
        },
        "BULK_PLAN_XID": {
          "type": "VARCHAR2(50)",
          "nullable": false,
          "info": "External identifier that is generated for each call to the bulk plan process. "
        },
        "QUERY_NAME": {
          "type": "VARCHAR2(120)",
          "nullable": true,
          "info": "Bulk plan input parameter. "
        },
        "START_TIME": {
          "type": "DATE",
          "nullable": true,
          "info": "Start time of the bulk plan. "
        },
        "END_TIME": {
          "type": "DATE",
          "nullable": true,
          "info": "End time of the bulk plan. "
        },
        "NUM_OF_ORDERS_SELECTED": {
          "type": "NUMBER()",
          "nullable": false,
          "info": "Number of orders selected from the database by the bulk plan. "
        },
        "NUM_OF_ORDERS_UNASSIGNED": {
          "type": "NUMBER()",
          "nullable": false,
          "info": "Number of orders which was planned already but anassigned by the bulk plan. "
        },
        "NUM_OF_ORDERS_PLANNED": {
          "type": "NUMBER()",
          "nullable": false,
          "info": "Number of orders successfully planned by the bulk plan. "
        },
        "NUM_OF_SHIPMENTS_BUILT": {
          "type": "NUMBER()",
          "nullable": false,
          "info": "Number of shipments generated by the bulk plan. "
        },
        "NUM_ORDERS_PLANNED_FAILED": {
          "type": "NUMBER()",
          "nullable": false
        },
        "PERSPECTIVE": {
          "type": "VARCHAR2(1)",
          "nullable": true,
          "values": [
            "B",
            "S"
          ],
          "info": "Must be B, S, or null. "
        },
        "LOG_PROCESS_ID": {
          "type": "NUMBER()",
          "nullable": true
        },
        "APP_MACHINE_GID": {
          "type": "VARCHAR2(101)",
          "nullable": true,
          "foreign_key": "APP_MACHINE"
        },
        "DOMAIN_NAME": {
          "type": "VARCHAR2(50)",
          "nullable": false
        },
        "PLANNING_PARAMETER_SET_GID": {
          "type": "VARCHAR2(101)",
          "nullable": false
        },
        "NUM_ORDER_MOVEMENTS_SELECTED": {
          "type": "NUMBER()",
          "nullable": true
        },
        "NUM_ORDER_MOVEMENTS_UNASSIGNED": {
          "type": "NUMBER()",
          "nullable": true
        },
        "NUM_ORDER_MOVEMENTS_PLANNED": {
          "type": "NUMBER()",
          "nullable": true
        },
        "NUM_ORDER_MOVEMENTS_FAILED": {
          "type": "NUMBER()",
          "nullable": true
        },
        "NUM_ORDERS_EXCLUDED": {
          "type": "NUMBER()",
          "nullable": true
        },
        "NUM_ORDER_MOVEMENTS_EXCLUDED": {
          "type": "NUMBER()",
          "nullable": true
        },
        "TOTAL_COST": {
          "type": "NUMBER()",
          "nullable": true
        },
        "TOTAL_COST_CURRENCY_GID": {
          "type": "VARCHAR2(101)",
          "nullable": true,
          "foreign_key": "CURRENCY"
        },
        "TOTAL_COST_BASE": {
          "type": "NUMBER()",
          "nullable": true
        },
        "TOTAL_WEIGHT": {
          "type": "NUMBER()",
          "nullable": true
        },
        "TOTAL_WEIGHT_UOM_CODE": {
          "type": "VARCHAR2(64)",
          "nullable": true
        },
        "TOTAL_WEIGHT_BASE": {
          "type": "NUMBER()",
          "nullable": true
        },
        "TOTAL_VOLUME": {
          "type": "NUMBER()",
          "nullable": true
        },
        "TOTAL_VOLUME_UOM_CODE": {
          "type": "VARCHAR2(64)",
          "nullable": true
        },
        "TOTAL_VOLUME_BASE": {
          "type": "NUMBER()",
          "nullable": true
        },
        "TOTAL_DISTANCE": {
          "type": "NUMBER()",
          "nullable": true
        },
        "TOTAL_DISTANCE_UOM_CODE": {
          "type": "VARCHAR2(64)",
          "nullable": true
        },
        "TOTAL_DISTANCE_BASE": {
          "type": "NUMBER()",
          "nullable": true
        },
        "TOTAL_NUM_STOPS": {
          "type": "NUMBER()",
          "nullable": true
        },
        "STATE": {
          "type": "VARCHAR2(50)",
          "nullable": false,
          "values": [
            "SUBMITTED",
            "RUNNING",
            "COMPLETED",
            "INTERRUPTED",
            "TERMINATED"
          ],
          "info": "Execution state of the bulkplan. INTERRUPTED when a user has requested termination but the bulkplan is still running. TERMINATED when the bulkplan completes termination. "
        },
        "SINCE": {
          "type": "DATE",
          "nullable": true,
          "info": "Time of last state change "
        },
        "DESCRIPTION": {
          "type": "VARCHAR2(4000)",
          "nullable": true,
          "info": "A description of the bulkplan used to identify a set of performance or quality conditions. Used to summarize the bulkplan assumptions when comparing multiple plans. "
        },
        "SCENARIO_GROUP": {
          "type": "VARCHAR2(100)",
          "nullable": true,
          "info": "A unique ID to identify a set of bulkplans for comparison "
        },
        "SHIPMENTS_SUPPRESSED": {
          "type": "VARCHAR2(1)",
          "nullable": false,
          "values": [
            "Y",
            "N"
          ],
          "info": "If Y, shipments were not commited to the database. This is a what-if scenario. "
        },
        "TERMINATION_TIME": {
          "type": "DATE",
          "nullable": true,
          "info": "Time when the bulkplan was terminated or timed out "
        },
        "TERMINATION_USER": {
          "type": "VARCHAR2(128)",
          "nullable": true,
          "foreign_key": "GL_USER",
          "info": "User who terminated the bulkplan "
        },
        "TERMINATION_REASON": {
          "type": "VARCHAR2(2000)",
          "nullable": true,
          "info": "Reason the bulkplan was terminated "
        },
        "TOTAL_SHIPMENT_TIME_SECS": {
          "type": "NUMBER()",
          "nullable": true,
          "info": "Sum of all shipments times (end-start) in seconds "
        },
        "TOTAL_WEIGHT_CAPACITY": {
          "type": "NUMBER()",
          "nullable": true,
          "info": "Sum of all shipment weight capacities (based on equipment used) "
        },
        "TOTAL_WEIGHT_CAPACITY_UOM_CODE": {
          "type": "VARCHAR2(64)",
          "nullable": true
        },
        "TOTAL_WEIGHT_CAPACITY_BASE": {
          "type": "NUMBER()",
          "nullable": true
        },
        "TOTAL_VOLUME_CAPACITY": {
          "type": "NUMBER()",
          "nullable": true,
          "info": "Sum of all shipment volume capacities (based on equipment used) "
        },
        "TOTAL_VOLUME_CAPACITY_UOM_CODE": {
          "type": "VARCHAR2(64)",
          "nullable": true
        },
        "TOTAL_VOLUME_CAPACITY_BASE": {
          "type": "NUMBER()",
          "nullable": true
        },
        "NUM_OF_ORDERS_THRU_POOL": {
          "type": "NUMBER()",
          "nullable": true,
          "info": "Number of orders that went through a pool point "
        },
        "NUM_OF_ORDERS_THRU_XDOCK": {
          "type": "NUMBER()",
          "nullable": true,
          "info": "Number of orders that went through a crossdock "
        },
        "TOTAL_BEST_DIRECT_COST": {
          "type": "NUMBER()",
          "nullable": true,
          "info": "Total best direct cost of planned orders "
        },
        "TOTAL_BEST_DIRECT_COST_CUR": {
          "type": "VARCHAR2(101)",
          "nullable": true,
          "foreign_key": "CURRENCY"
        },
        "TOTAL_BEST_DIRECT_COST_BASE": {
          "type": "NUMBER()",
          "nullable": true
        },
        "INSERT_USER": {
          "type": "VARCHAR2(128)",
          "nullable": false
        },
        "INSERT_DATE": {
          "type": "DATE",
          "nullable": false
        },
        "UPDATE_USER": {
          "type": "VARCHAR2(128)",
          "nullable": true
        },
        "UPDATE_DATE": {
          "type": "DATE",
          "nullable": true
        },
        "TOTAL_ACTUAL_COST": {
          "type": "NUMBER()",
          "nullable": true
        },
        "TOTAL_ACTUAL_COST_BASE": {
          "type": "NUMBER()",
          "nullable": true
        },
        "TOTAL_ACTUAL_COST_CURRENCY_GID": {
          "type": "VARCHAR2(101)",
          "nullable": true,
          "foreign_key": "CURRENCY"
        },
        "NUM_OF_WA_CREATED": {
          "type": "NUMBER()",
          "nullable": false,
          "info": "Number of Work assignments created during the Bulk plan process. "
        },
        "PROJECT_GID": {
          "type": "VARCHAR2(101)",
          "nullable": true,
          "info": "Captures the project_gid (lnm_project table) for which this bulkplan is created. "
        },
        "SCENARIO_GID": {
          "type": "VARCHAR2(101)",
          "nullable": true,
          "info": "Captures the scenario_gid (lnm_scenario table) for which this bulkplan is created. "
        },
        "WORK_ASSIGNMENT_BULK_PLAN_GID": {
          "type": "VARCHAR2(101)",
          "nullable": true,
          "foreign_key": "WORK_ASSIGNMENT_BULK_PLAN",
          "info": "Work assignment bulk plan id which is generated during work assignment bulk plan process."
        }
      },
      "fk_tables": [
        "BULK_CM",
        "BULK_PLAN_BY_MODE",
        "BULK_PLAN_BY_SERVPROV",
        "BULK_PLAN_MILESTONE",
        "BULK_PLAN_PARTITION",
        "ORDER_MOVEMENT",
        "ORDER_RELEASE",
        "SHIPMENT"
      ]
    }
  }
};
