// CURRENCY.js

window.CURRENCY = {
  "tables": {
    "CURRENCY": {
      "columns": {
        "CURRENCY_GID": {
          "type": "VARCHAR2(101)",
          "nullable": false,
          "key_value": true,
          "info": "CURRENCY_GID contains the unique identifier for the currency. Examples include USD for US dollars and DEM for Deutsche marks. "
        },
        "CURRENCY_XID": {
          "type": "VARCHAR2(50)",
          "nullable": false,
          "info": "CURRENCY_XID contains the unique external identifier for the currency. "
        },
        "CURRENCY_NAME": {
          "type": "VARCHAR2(120)",
          "nullable": true,
          "info": "CURRENCY_NAME contains the proper name for a currency. Examples include pesos and rupees. "
        },
        "COUNTRY_CODE3_GID": {
          "type": "VARCHAR2(101)",
          "nullable": true,
          "foreign_key": "COUNTRY_CODE",
          "info": "GC3 Global identifier for the entity. Is created by concatenating Domain Name,\".\" and XID."
        },
        "DOMAIN_NAME": {
          "type": "VARCHAR2(50)",
          "nullable": false
        },
        "INSERT_USER": {
          "type": "VARCHAR2(128)",
          "nullable": false
        },
        "INSERT_DATE": {
          "type": "DATE",
          "nullable": false
        },
        "UPDATE_USER": {
          "type": "VARCHAR2(128)",
          "nullable": true
        },
        "UPDATE_DATE": {
          "type": "DATE",
          "nullable": true
        }
      },
      "fk_tables": [
        "ACCESSORIAL_COST",
        "ACCESSORIAL_COST_UNIT_BREAK",
        "ALLOCATION",
        "ALLOCATION_BASE",
        "ALLOCATION_D",
        "ALLOCATION_OB_LINE",
        "ALLOCATION_OB_LINE_D",
        "ALLOCATION_ORDER_RELEASE_D",
        "ALLOCATION_OR_LINE_D",
        "ASSET_LEASE",
        "AUTO_APPROVE_RULE",
        "AUTO_APPROVE_RULE_DETAIL",
        "BULK_CM",
        "BULK_PLAN",
        "BULK_PLAN_BY_MODE",
        "BULK_PLAN_BY_SERVPROV",
        "BULK_PLAN_PARTITION",
        "BULK_PLAN_PARTITION_BY_MODE",
        "BULK_PLAN_PARTITION_SERVPROV",
        "CLAIM",
        "CLAIM_COST",
        "CLAIM_LINE_ITEM",
        "CLAIM_LINE_ITEM_COST",
        "COMMERCIAL_INVOICE",
        "COMMERCIAL_INVOICE_CHARGE",
        "COMMIT_DOW_OVERRIDE",
        "COMMIT_USAGE",
        "CORPORATION",
        "CR_FLEET",
        "CR_FORECAST",
        "CR_LANE_COMMITMENT",
        "CR_LV_AGGREGATE",
        "CR_ROUTE",
        "CR_ROUTE_LEG",
        "CR_SCENARIO_SUMMARY",
        "CR_SOLUTION",
        "CURRENCY_EXCHANGE_RATE",
        "DM_TRANSACTION_LINEITEM",
        "DOMAIN_SETTING",
        "EQUIPMENT",
        "FLEET_BULK_PLAN",
        "FLEET_BULK_PLAN_COST",
        "GTM_BOND",
        "GTM_CA_LINE_VALUE",
        "GTM_LICENSE_LINE",
        "GTM_LICENSE_LINE_USAGE",
        "GTM_LICENSE_LINE_VALUE",
        "GTM_REGIME",
        "GTM_REGISTRATION_VALUE",
        "GTM_STRUCTURE_VALUE",
        "GTM_STR_COMPONENT_CURRENCY",
        "GTM_TRANSACTION",
        "GTM_TRANSACTION_VALUE",
        "GTM_TRANS_LINE_LICENSE",
        "GTM_TRANS_LINE_VALUE",
        "INVOICE",
        "INVOICE_LINEITEM",
        "INVOICE_LINEITEM_VAT",
        "INVOICE_LINEITEM_VAT_COST_REF",
        "INVOICE_LI_COMMERCIAL_DATA",
        "INVOICE_SUMMARY",
        "INVOICE_SUMMARY_DETAIL",
        "ITEM",
        "ITEM_ORIGIN_VALUE",
        "ITEM_QF_VALUE",
        "ITINERARY",
        "LEG",
        "LINE_APPROVE_TOLERANCE_DETAIL",
        "LOCATION_CAPACITY_D",
        "LOCATION_CAPACITY_OVERRIDE",
        "LOCATION_ROLE_PROFILE",
        "LOGISTICS_GUIDE_TEMPLATE",
        "NFRC_RULE",
        "OB_LINE",
        "OB_ORDER_BASE",
        "OB_SHIP_UNIT",
        "OB_SHIP_UNIT_CONTENT",
        "ORDER_MOVEMENT",
        "ORDER_RELEASE",
        "ORDER_RELEASE_ACCRUAL",
        "ORDER_RELEASE_LINE",
        "P_BID",
        "P_LANE_ATTRIBUTES",
        "P_RULE_FAVOR_BY_ATTRIB",
        "P_RULE_FAVOR_CARRIER",
        "P_RULE_LIMIT_AWARD",
        "P_RULE_WIN_CARRIER_LIMIT",
        "P_SHIPMENT",
        "QUOTE_COST_OPTION",
        "QUOTE_COST_OPTION_SHIPMENT",
        "QUOTE_COST_OPTION_SHIP_COST",
        "QUOTE_SHIP_UNIT",
        "RATE_GEO",
        "RATE_GEO_COST",
        "RATE_GEO_COST_UNIT_BREAK",
        "RATE_GEO_COST_WEIGHT_BREAK",
        "RATE_GEO_STOPS",
        "RATE_OFFERING",
        "RATE_OFFERING_STOPS",
        "RATE_QUALITY",
        "RATE_SERVICE",
        "ROUTE_TEMPLATE",
        "SERVPROV_POLICY",
        "SHIPMENT",
        "SHIPMENT_COST",
        "SHIPMENT_INF_COST",
        "SHIPMENT_INF_COST_D",
        "SHIPPING_AGENT_CONTACT",
        "SHIPPING_AGENT_CONTACT_PROFIT",
        "SKU_COST",
        "S_SHIP_UNIT_LINE",
        "TENDER_COLLABORATION",
        "TENDER_COLLAB_SERVPROV",
        "VAT_ANALYSIS",
        "VOUCHER",
        "VOUCHER_INVOICE_LINEITEM_JOIN",
        "VOUCHER_VAT_ANALYSIS",
        "WORK_ASSIGNMENT",
        "WORK_INVOICE"
      ]
    }
  }
};
