// OTM_RELEASE.js

window.OTM_RELEASE = {
  "tables": {
    "OTM_RELEASE": {
      "columns": {
        "OTM_RELEASE_GID": {
          "type": "VARCHAR2(101)",
          "nullable": false,
          "key_value": true,
          "info": "Release ID - full release string "
        },
        "OTM_RELEASE_XID": {
          "type": "VARCHAR2(50)",
          "nullable": false
        },
        "SORTABLE_VERSION": {
          "type": "NUMBER()",
          "nullable": false,
          "info": "A number representing the ordered position of the release among all other releases. "
        },
        "DESCRIPTION": {
          "type": "VARCHAR2(1000)",
          "nullable": true,
          "info": "Optional description of the release"
        },
        "DOMAIN_NAME": {
          "type": "VARCHAR2(50)",
          "nullable": false
        },
        "INSERT_USER": {
          "type": "VARCHAR2(128)",
          "nullable": false
        },
        "INSERT_DATE": {
          "type": "DATE",
          "nullable": false
        },
        "UPDATE_USER": {
          "type": "VARCHAR2(128)",
          "nullable": true
        },
        "UPDATE_DATE": {
          "type": "DATE",
          "nullable": true
        }
      },
      "fk_tables": [
        "ACTION",
        "ACTION_ARG",
        "ACTION_DEF",
        "ACTION_DEF_ARG",
        "ACTION_DEF_SEL_PARAM",
        "ACTION_DEF_STATE",
        "ACTION_DRAG",
        "ADVANCED_LAYOUT_XML",
        "AGENT",
        "AGENT_ACTION",
        "AGENT_ACTION_DETAILS",
        "AGENT_EVENT",
        "AGENT_EVENT_COLUMN_MAPPING",
        "AGENT_EVENT_DETAILS",
        "AGENT_EVENT_TABLE_MAPPING",
        "ALLOCATION_RULE_DETAIL",
        "ALLOC_METHOD",
        "ALLOC_METHOD_DETAIL",
        "ALLOC_METRIC",
        "ALLOC_TARGET",
        "APP_ACTION",
        "APP_ACTION_RESP_PARTY_P",
        "APP_SHARED_ITEM",
        "AUDIT_OBJECT_TYPE",
        "AUTO_ASSIGN_CRITERIA",
        "AUTO_ASSIGN_TYPE",
        "AUTO_ASSIGN_TYPE_CRIT_MAP",
        "AUTO_ASSIGN_TYPE_DQ_MAP",
        "BN_CHECKSUM_ALGORITHM",
        "BN_CONTEXT",
        "BN_GENERATOR",
        "BN_RULE",
        "BN_TYPE",
        "BS_EVENT_GROUP",
        "BS_EVENT_GROUP_ATTRIBUTE",
        "BS_EVENT_GROUP_CLASSIFY",
        "BS_QUICK_CODE",
        "BS_STATUS_GROUP",
        "BS_STATUS_GROUP_PROFILE_D",
        "BUSINESS_MONITOR_D",
        "CR_FORECAST_RULE",
        "DATA_QUERY_TYPE",
        "DATA_QUEUE_DEF",
        "DATA_QUEUE_EXECUTOR",
        "DATA_QUEUE_POLLER",
        "DATA_QUEUE_POLLER_INDEX",
        "DATA_Q_DEF_RELATED_Q_DEF",
        "DATA_TYPE_ASSOCIATION",
        "DEPENDENCY_SERVICE_D",
        "DERIVED_DATA_OP_IMPL",
        "DERIVED_FIELD",
        "DERIVED_FIELD_PARAMETER",
        "DERIVED_FIELD_PARAM_DISP_OP",
        "DIAG_PERFORMANCE_CAPTURE",
        "DIAG_STATIC_CAPTURE",
        "DISTANCE_EXTERNAL_ENGINE",
        "DISTANCE_EXTERNAL_GEO",
        "DOCUMENT_DEF",
        "DOCUMENT_DEF_CHECK",
        "DOCUMENT_DEF_OWNER_DETAILS",
        "DOCUMENT_DEF_TEXT",
        "EXTERNAL_ENGINE_PARAM",
        "EXTERNAL_ENGINE_PARAM_VALUE",
        "EXTERNAL_RATING_ENGINE",
        "FINDER_LINK",
        "FINDER_SET",
        "FINDER_SET_XML",
        "GL_KEY_COMPONENT_TYPE",
        "GL_KEY_COMPONENT_TYPE_PARAM",
        "GTM_CONSTRAINT_TYPE",
        "GTM_CRULE_ACTION_DEF",
        "GTM_CSET_TYPE_C_TYPE_MAP",
        "GTM_DT_ATTRIBUTE_DEF",
        "GTM_FORMULA_EXP_IDENTIFIER",
        "GTM_OBJECT_TYPE_ATTRIBUTE",
        "GTM_REGIME_DOCUMENT_DEF",
        "GTM_TRANS_REFNUM_QUAL",
        "JAVA_PLUGIN",
        "LOGIC_CONFIG",
        "LOGIC_CONFIG_GROUP",
        "LOGIC_PARAMETER",
        "LOGIC_PARAMETER_QUALIFIER",
        "MANAGER_LAYOUT",
        "MANAGER_LAYOUT_XML",
        "MESSAGE_TYPE",
        "MONITOR_BUSINESS_FUNCTION",
        "MONITOR_OPERAND_D",
        "NOTIFY_SUBJECT",
        "NOTIFY_SUBJECT_STYLESHEET",
        "OPT_FEATURE",
        "OPT_FEATURE_PROPERTY",
        "OUT_XML_PROFILE_D",
        "PARAMETER_GROUP",
        "PLANNING_PARAMETER",
        "PLANNING_PARAMETER_QUALIFIER",
        "POWERDATA_LAYOUT_XML",
        "PREFERENCE",
        "PROCESS_CONTROL_REQUEST",
        "QUERY_TABLE",
        "RATABLE_OPERATOR",
        "RATE_ATTRIBUTE",
        "RATE_ATTRIBUTE_JOIN",
        "RATE_COSTING_SEQUENCE",
        "RATE_GEO_COST_OPERAND",
        "RATE_GEO_COST_OP_OWNER",
        "RATE_SERVICE",
        "RATE_SERVICE_SPEED",
        "REPORT",
        "REPORT_PARAMETER",
        "ROT_RATE_OPERAND_VISIBILITY",
        "RULE",
        "RULE_SET_JOIN",
        "SAVED_CONDITION",
        "SAVED_CONDITION_QUERY",
        "SAVED_QUERY",
        "SAVED_QUERY_VALUES",
        "SERVICE_EXTERNAL_ENGINE",
        "SERVICE_EXTERNAL_ENGINE_PARM",
        "SERVICE_TIME",
        "SHIPMENT_REFNUM_QUAL",
        "SHIPPING_AGENT_RULE",
        "SHIPPING_AGENT_TYPE_D",
        "STATUS_FUNCTOR",
        "STATUS_TYPE",
        "STATUS_VALUE",
        "STYLESHEET_CONTENT",
        "STYLESHEET_PROFILE",
        "STYLESHEET_PROFILE_LOCALE",
        "TEXT_TEMPLATE",
        "TOPIC_ALIAS",
        "TRANSPORTATION_WORKBENCH_XML",
        "UOMMAP",
        "USER_MENU_LAYOUT_XML",
        "VALID_VALUE",
        "VALID_VALUE_TYPE",
        "WORKFLOW_INFO",
        "WORKFLOW_PARAM",
        "WORKFLOW_TOPIC_INFO",
        "WORKFLOW_TOPIC_PARAM",
        "WORK_QUEUE",
        "XML_BUILDER"
      ]
    }
  }
};
