// REPORT_LOG.js

window.REPORT_LOG = {
  "tables": {
    "REPORT_LOG": {
      "columns": {
        "FILE_NAME": {
          "type": "VARCHAR2(100)",
          "nullable": false,
          "key_value": true,
          "info": "Filename generated by the report program. For forms that need to be stored for each run a new filename will be generated. For operational reports where only the current run pdf file is needed, an update will be done with the same file name. "
        },
        "REPORT_GID": {
          "type": "VARCHAR2(101)",
          "nullable": false,
          "foreign_key": "REPORT",
          "info": "GC3 Global indetifier for the entity. Is created by concatenating Domain Name,\".\" and XID. "
        },
        "JOB_NUMBER": {
          "type": "NUMBER(10)",
          "nullable": false,
          "info": "Running sequence generated by the BN number generator "
        },
        "GL_USER_GID": {
          "type": "VARCHAR2(128)",
          "nullable": true,
          "foreign_key": "GL_USER",
          "info": "GC3 Global indetifier for the entity. Is created by concatenating Domain Name,\".\" and XID. "
        },
        "RUN_DATE": {
          "type": "DATE",
          "nullable": false,
          "info": "The date/time when the report was run "
        },
        "REPORT_SENT": {
          "type": "VARCHAR2(1)",
          "nullable": false,
          "values": [
            "Y",
            "N",
            "F"
          ]
        },
        "DOMAIN_NAME": {
          "type": "VARCHAR2(50)",
          "nullable": false,
          "info": "Domain of the User. Is used for creating the GID. "
        },
        "REPORT_SET_GID": {
          "type": "VARCHAR2(101)",
          "nullable": true,
          "foreign_key": "REPORT_SET",
          "info": "The report set that this report was run for (this can be null). "
        },
        "INSERT_USER": {
          "type": "VARCHAR2(128)",
          "nullable": false,
          "info": "For audit trail purposes. This field stores the id of the user who first entered the record. "
        },
        "INSERT_DATE": {
          "type": "DATE",
          "nullable": false,
          "info": "For audit trail purposes. This field stores the date and time when the record was first entered in the database. "
        },
        "UPDATE_USER": {
          "type": "VARCHAR2(128)",
          "nullable": true,
          "info": "For audit trail purposes. This field stores the id of the user who last updated the record. "
        },
        "UPDATE_DATE": {
          "type": "DATE",
          "nullable": true,
          "info": "For audit trail purposes. This field stores the date and time when the record was updated in the database. "
        },
        "BULK_REPORTING_GID": {
          "type": "VARCHAR2(101)",
          "nullable": true,
          "foreign_key": "BULK_REPORTING",
          "info": "If the report is part of a bulk report generation, the ID for monitoring"
        }
      },
      "fk_tables": [
        "REPORT_LOG_PARAMETER"
      ]
    }
  }
};
