// REPORT_EMAIL.js

window.REPORT_EMAIL = {
  "tables": {
    "REPORT_EMAIL": {
      "columns": {
        "REPORT_GID": {
          "type": "VARCHAR2(101)",
          "nullable": false,
          "key_value": true,
          "foreign_key": "REPORT",
          "info": "GC3 Global indetifier for the entity. Is created by concatenating Domain Name,\".\" and XID. "
        },
        "REPORT_JOB_NUMBER": {
          "type": "NUMBER()",
          "nullable": false,
          "key_value": true,
          "info": "Running sequence generated by the BN number generator "
        },
        "EMAIL_ADDRESS": {
          "type": "VARCHAR2(100)",
          "nullable": false,
          "key_value": true,
          "info": "E-Mail address as entered in the screen "
        },
        "DOMAIN_NAME": {
          "type": "VARCHAR2(50)",
          "nullable": false,
          "info": "Domain of the User. Is used for creating the GID. "
        },
        "REPORT_SENT": {
          "type": "VARCHAR2(1)",
          "nullable": false
        },
        "INSERT_USER": {
          "type": "VARCHAR2(128)",
          "nullable": false,
          "info": "For audit trail purposes. This field stores the id of the user who first entered the record. "
        },
        "INSERT_DATE": {
          "type": "DATE",
          "nullable": false,
          "info": "For audit trail purposes. This field stores the date and time when the record was first entered in the database. "
        },
        "UPDATE_USER": {
          "type": "VARCHAR2(128)",
          "nullable": true,
          "info": "For audit trail purposes. This field stores the id of the user who last updated the record. "
        },
        "UPDATE_DATE": {
          "type": "DATE",
          "nullable": true,
          "info": "For audit trail purposes. This field stores the date and time when the record was updated in the database. "
        },
        "SCHEDULE": {
          "type": "VARCHAR2(100)",
          "nullable": false,
          "info": "The schedule created by the user in a string format "
        },
        "EMAIL_SUBJECT": {
          "type": "VARCHAR2(1000)",
          "nullable": true,
          "info": "E-mail subject override "
        },
        "EMAIL_BODY": {
          "type": "VARCHAR2(2000)",
          "nullable": true,
          "info": "E-mail body override "
        },
        "EMAIL_HOST": {
          "type": "VARCHAR2(1000)",
          "nullable": true,
          "info": "E-mail SMTP host override"
        }
      },
      "fk_tables": []
    }
  }
};
