// SHIP_UNIT.js

window.SHIP_UNIT = {
  "tables": {
    "SHIP_UNIT": {
      "columns": {
        "SHIP_UNIT_GID": {
          "type": "VARCHAR2(101)",
          "nullable": false,
          "key_value": true,
          "info": "The GID for the ship unit associated to an order release. "
        },
        "SHIP_UNIT_XID": {
          "type": "VARCHAR2(50)",
          "nullable": false,
          "info": "The XID for the ship unit associated to a order release. "
        },
        "IS_SPLITABLE": {
          "type": "CHAR(1)",
          "nullable": false,
          "info": "A Y/N flag to identify if the ship unit can be split when creating an order. "
        },
        "TRANSPORT_HANDLING_UNIT_GID": {
          "type": "VARCHAR2(101)",
          "nullable": true,
          "foreign_key": "SHIP_UNIT_SPEC",
          "info": "The transport handling unit identifier defined for the ship unit. Examples are a box and a pallet. "
        },
        "UNIT_LENGTH": {
          "type": "NUMBER()",
          "nullable": true,
          "info": "The length of each order release ship unit. If this row represents 20 of the same ship units, the total length is 20 x unit length. "
        },
        "UNIT_LENGTH_UOM_CODE": {
          "type": "VARCHAR2(64)",
          "nullable": true,
          "info": "The unit of measure for the unit length column. "
        },
        "UNIT_LENGTH_BASE": {
          "type": "NUMBER()",
          "nullable": true,
          "info": "The unit length in base units. "
        },
        "UNIT_WIDTH": {
          "type": "NUMBER()",
          "nullable": true,
          "info": "The width of each order release ship unit. Each row may represent the ship unit count number of same ship units. If this field is null or is 0, the weight of this order release ship unit is computed as the total of container weight from its ship unit specification and the weight of its shipment ship unit lines. "
        },
        "UNIT_WIDTH_UOM_CODE": {
          "type": "VARCHAR2(64)",
          "nullable": true,
          "info": "The unit of measure for the unit width. "
        },
        "UNIT_WIDTH_BASE": {
          "type": "NUMBER()",
          "nullable": true,
          "info": "The unit width in base units. "
        },
        "UNIT_HEIGHT": {
          "type": "NUMBER()",
          "nullable": true,
          "info": "The height of each order release ship unit. If this row represents the 20 same ship units, the total height is 20 x unit height. "
        },
        "UNIT_HEIGHT_UOM_CODE": {
          "type": "VARCHAR2(64)",
          "nullable": true,
          "info": "The unit of measure for unit height column. "
        },
        "UNIT_HEIGHT_BASE": {
          "type": "NUMBER()",
          "nullable": true,
          "info": "The unit height in base units. "
        },
        "UNIT_WEIGHT": {
          "type": "NUMBER()",
          "nullable": true,
          "info": "The weight of the ship unit. "
        },
        "UNIT_WEIGHT_UOM_CODE": {
          "type": "VARCHAR2(64)",
          "nullable": true,
          "info": "The unit of measure for the unit weight. "
        },
        "UNIT_WEIGHT_BASE": {
          "type": "NUMBER()",
          "nullable": true,
          "info": "The unit weight in base units. "
        },
        "UNIT_VOLUME": {
          "type": "NUMBER()",
          "nullable": true,
          "info": "The volume of each order release ship unit. Each row may represent the ship unit count number of same ship units. If this field is null or is 0, the volume of this shipment ship unit is computed as the total of container volume from its ship unit specification and the volume of its shipment ship unit lines. "
        },
        "UNIT_VOLUME_UOM_CODE": {
          "type": "VARCHAR2(64)",
          "nullable": true,
          "info": "The unit of measure for the unit volume. "
        },
        "UNIT_VOLUME_BASE": {
          "type": "NUMBER()",
          "nullable": true,
          "info": "The unit volume in base units. "
        },
        "FLEX_COMMODITY_CODE": {
          "type": "VARCHAR2(101)",
          "nullable": true,
          "info": "The user defined commodity code for the item. E.g.. the HTS, NMFC, SITC, STCC codes for the item. "
        },
        "FLEX_COMMODITY_QUAL_GID": {
          "type": "VARCHAR2(101)",
          "nullable": true,
          "foreign_key": "FLEX_COMMODITY_QUAL",
          "info": "A unique identifier to define the type of the code. E.g.. HTS, SITC, STCC, NMFC etc. "
        },
        "IS_SYSTEM_GENERATED": {
          "type": "CHAR(1)",
          "nullable": false,
          "values": [
            "Y",
            "N"
          ],
          "info": "A Y/N indicator to define if the record is generated by the system for the order base or copied (may be from XML). "
        },
        "ORDER_RELEASE_GID": {
          "type": "VARCHAR2(101)",
          "nullable": false,
          "foreign_key": "OR_EQUIPMENT",
          "info": "The order release associated to this ship unit. "
        },
        "OR_EQUIPMENT_SEQ": {
          "type": "NUMBER(3)",
          "nullable": true,
          "foreign_key": "OR_EQUIPMENT",
          "info": "Associates equipment of the order release to this particular ship unit. "
        },
        "SHIP_UNIT_COUNT": {
          "type": "NUMBER(10)",
          "nullable": false,
          "info": "Ship units that have the same dimension/weight and contents are represented as one row in the SHIP_UNIT table. The ship unit count is the number of these ship units. "
        },
        "OB_SHIP_UNIT_GID": {
          "type": "VARCHAR2(101)",
          "nullable": true,
          "foreign_key": "OB_SHIP_UNIT",
          "info": "The order base ship unit associated with the order release ship unit if it was created from an order base and the releasing logic. "
        },
        "UNIT_NET_WEIGHT": {
          "type": "NUMBER()",
          "nullable": true,
          "info": "The net weight of the ship unit. "
        },
        "UNIT_NET_WEIGHT_UOM_CODE": {
          "type": "VARCHAR2(64)",
          "nullable": true,
          "info": "The unit of measure for the unit net weight. "
        },
        "UNIT_NET_WEIGHT_BASE": {
          "type": "NUMBER()",
          "nullable": true,
          "info": "The unit net weight in base units. "
        },
        "UNIT_NET_VOLUME": {
          "type": "NUMBER()",
          "nullable": true,
          "info": "The net volume of the ship unit. "
        },
        "UNIT_NET_VOLUME_UOM_CODE": {
          "type": "VARCHAR2(64)",
          "nullable": true,
          "info": "The unit of measure for the unit net volume. "
        },
        "UNIT_NET_VOLUME_BASE": {
          "type": "NUMBER()",
          "nullable": true,
          "info": "The unit net volume in base units. "
        },
        "SECONDARY_UNIT_WEIGHT": {
          "type": "NUMBER()",
          "nullable": true,
          "info": "An additional value for the secondary gross weight of the ship unit. "
        },
        "SECONDARY_UNIT_WEIGHT_UOM_CODE": {
          "type": "VARCHAR2(64)",
          "nullable": true,
          "info": "Unit of measure for secondary weight column. "
        },
        "SECONDARY_UNIT_WEIGHT_BASE": {
          "type": "NUMBER()",
          "nullable": true,
          "info": "The secondary weight in base units. "
        },
        "SECONDARY_UNIT_VOLUME": {
          "type": "NUMBER()",
          "nullable": true,
          "info": "An additional value for the secondary gross volume of the ship unit. "
        },
        "SECONDARY_UNIT_VOLUME_UOM_CODE": {
          "type": "VARCHAR2(64)",
          "nullable": true,
          "info": "Unit of measure for the secondary volume. "
        },
        "SECONDARY_UNIT_VOLUME_BASE": {
          "type": "NUMBER()",
          "nullable": true,
          "info": "The secondary volume in base units. "
        },
        "SECONDRY_UNIT_NET_WT": {
          "type": "NUMBER()",
          "nullable": true,
          "info": "An additional value for the secondary net weight of the ship unit. "
        },
        "SECONDRY_UNIT_NET_WT_UOM_CODE": {
          "type": "VARCHAR2(64)",
          "nullable": true,
          "info": "Unit of measure for secondary net weight column. "
        },
        "SECONDRY_UNIT_NET_WT_BASE": {
          "type": "NUMBER()",
          "nullable": true,
          "info": "The secondary net weight in base units. "
        },
        "SECONDRY_UNIT_NET_VOL": {
          "type": "NUMBER()",
          "nullable": true,
          "info": "An additional value for the secondary net volume of the ship unit. "
        },
        "SECONDRY_UNIT_NET_VOL_UOM_CODE": {
          "type": "VARCHAR2(64)",
          "nullable": true,
          "info": "Unit of measure for the net secondary volume. "
        },
        "SECONDRY_UNIT_NET_VOL_BASE": {
          "type": "NUMBER()",
          "nullable": true,
          "info": "The secondary net volume in base units. "
        },
        "CORE_DIAMETER": {
          "type": "NUMBER()",
          "nullable": true,
          "info": "For cylindrical objects, this defines the diameter of the core "
        },
        "CORE_DIAMETER_UOM_CODE": {
          "type": "VARCHAR2(64)",
          "nullable": true,
          "info": "The unit of measure for the diameter of the core "
        },
        "CORE_DIAMETER_BASE": {
          "type": "NUMBER()",
          "nullable": true,
          "info": "The diameter of the core in the base unit of measure. "
        },
        "UNIT_DIAMETER": {
          "type": "NUMBER()",
          "nullable": true,
          "info": "The unit diameter of the ship unit. "
        },
        "UNIT_DIAMETER_UOM_CODE": {
          "type": "VARCHAR2(64)",
          "nullable": true,
          "info": "Unit of measure for the unit diameter. "
        },
        "UNIT_DIAMETER_BASE": {
          "type": "NUMBER()",
          "nullable": true,
          "info": "The unit diameter in the base unit of measure. "
        },
        "TAG_1": {
          "type": "VARCHAR2(101)",
          "nullable": true,
          "info": "A flexible field to contain informational data that has been copied from the order to the shipment. "
        },
        "TAG_2": {
          "type": "VARCHAR2(101)",
          "nullable": true,
          "info": "A flexible field to contain informational data that has been copied from the order to the shipment. "
        },
        "TAG_3": {
          "type": "VARCHAR2(101)",
          "nullable": true,
          "info": "A flexible field to contain informational data that has been copied from the order to the shipment. "
        },
        "TAG_4": {
          "type": "VARCHAR2(101)",
          "nullable": true,
          "info": "A flexible field to contain informational data that has been copied from the order to the shipment. "
        },
        "OB_SU_RELEASE_INSTR_SEQ": {
          "type": "NUMBER(10)",
          "nullable": true,
          "info": "The release instruction associated to the order base if the order release was created from an order base through the releasing logic. "
        },
        "IS_COUNT_SPLITTABLE": {
          "type": "VARCHAR2(1)",
          "nullable": true,
          "values": [
            "Y",
            "N"
          ],
          "info": "A Y/N indicator for whether the ship unit can be split on the count boundaries when planning during container optimization. "
        },
        "PICKUP_OR_STOP_GID": {
          "type": "VARCHAR2(101)",
          "nullable": true,
          "foreign_key": "OR_STOP",
          "info": "This ship unit is going to be picked up at this stop. If this field is empty, this ship unit is picked up at the order's source location. "
        },
        "DROPOFF_OR_STOP_GID": {
          "type": "VARCHAR2(101)",
          "nullable": true,
          "foreign_key": "OR_STOP",
          "info": "This ship unit is going to be dropped off at this stop. If this field is empty, this ship unit is dropped off at the order's destination location. "
        },
        "DOMAIN_NAME": {
          "type": "VARCHAR2(50)",
          "nullable": false,
          "info": "Database domain where this data is stored. "
        },
        "INSERT_USER": {
          "type": "VARCHAR2(128)",
          "nullable": false,
          "info": "The user ID of the data insert user. "
        },
        "INSERT_DATE": {
          "type": "DATE",
          "nullable": false,
          "info": "Date and time of data insert. "
        },
        "UPDATE_USER": {
          "type": "VARCHAR2(128)",
          "nullable": true,
          "info": "The user ID of the data update user. "
        },
        "UPDATE_DATE": {
          "type": "DATE",
          "nullable": true,
          "info": "Date and time of the most recent data update. "
        },
        "TOTAL_GROSS_WEIGHT": {
          "type": "NUMBER()",
          "nullable": true,
          "info": "The total gross weight of the order release ship unit (transport handling unit + lines). "
        },
        "TOTAL_GROSS_WEIGHT_BASE": {
          "type": "NUMBER()",
          "nullable": true,
          "info": "The total gross weight unit of measure. "
        },
        "TOTAL_GROSS_WEIGHT_UOM_CODE": {
          "type": "VARCHAR2(101)",
          "nullable": true,
          "info": "The total gross weight in the base unit of measure. "
        },
        "TOTAL_GROSS_VOLUME": {
          "type": "NUMBER()",
          "nullable": true,
          "info": "The total gross volume of the order release ship unit (transport handling unit + lines). "
        },
        "TOTAL_GROSS_VOLUME_BASE": {
          "type": "NUMBER()",
          "nullable": true,
          "info": "The total gross volume unit of measure. "
        },
        "TOTAL_GROSS_VOLUME_UOM_CODE": {
          "type": "VARCHAR2(101)",
          "nullable": true,
          "info": "The total gross volume in the base unit of measure. "
        },
        "LOAD_CONFIG_SETUP_GID": {
          "type": "VARCHAR2(101)",
          "nullable": true,
          "foreign_key": "LOAD_CONFIG_SETUP",
          "info": "A load configurator set up identifier to be used by the load configuration engine as the input rules for how the ship unit was built. "
        },
        "IS_ALLOW_REPACK": {
          "type": "VARCHAR2(1)",
          "nullable": true,
          "values": [
            "Y",
            "N"
          ],
          "info": "A Y/N field, if this flag is set to false, when planning order movement that contains this shipment ship unit or combine shipments that contains this shipment ship unit, the shipment ship unit building process will not repack this s ship unit. "
        },
        "ATTRIBUTE1": {
          "type": "VARCHAR2(150)",
          "nullable": true,
          "info": "Attribute fields (flexfields) allow you to add additional information about an object. Data type VARCHAR2 (150) "
        },
        "ATTRIBUTE2": {
          "type": "VARCHAR2(150)",
          "nullable": true,
          "info": "Attribute fields (flexfields) allow you to add additional information about an object. Data type VARCHAR2 (150) "
        },
        "ATTRIBUTE3": {
          "type": "VARCHAR2(150)",
          "nullable": true,
          "info": "Attribute fields (flexfields) allow you to add additional information about an object. Data type VARCHAR2 (150) "
        },
        "ATTRIBUTE4": {
          "type": "VARCHAR2(150)",
          "nullable": true,
          "info": "Attribute fields (flexfields) allow you to add additional information about an object. Data type VARCHAR2 (150) "
        },
        "ATTRIBUTE5": {
          "type": "VARCHAR2(150)",
          "nullable": true,
          "info": "Attribute fields (flexfields) allow you to add additional information about an object. Data type VARCHAR2 (150) "
        },
        "ATTRIBUTE6": {
          "type": "VARCHAR2(150)",
          "nullable": true,
          "info": "Attribute fields (flexfields) allow you to add additional information about an object. Data type VARCHAR2 (150) "
        },
        "ATTRIBUTE7": {
          "type": "VARCHAR2(150)",
          "nullable": true,
          "info": "Attribute fields (flexfields) allow you to add additional information about an object. Data type VARCHAR2 (150) "
        },
        "ATTRIBUTE8": {
          "type": "VARCHAR2(150)",
          "nullable": true,
          "info": "Attribute fields (flexfields) allow you to add additional information about an object. Data type VARCHAR2 (150) "
        },
        "ATTRIBUTE9": {
          "type": "VARCHAR2(150)",
          "nullable": true,
          "info": "Attribute fields (flexfields) allow you to add additional information about an object. Data type VARCHAR2 (150) "
        },
        "ATTRIBUTE10": {
          "type": "VARCHAR2(150)",
          "nullable": true,
          "info": "Attribute fields (flexfields) allow you to add additional information about an object. Data type VARCHAR2 (150) "
        },
        "ATTRIBUTE11": {
          "type": "VARCHAR2(150)",
          "nullable": true,
          "info": "Attribute fields (flexfields) allow you to add additional information about an object. Data type VARCHAR2 (150) "
        },
        "ATTRIBUTE12": {
          "type": "VARCHAR2(150)",
          "nullable": true,
          "info": "Attribute fields (flexfields) allow you to add additional information about an object. Data type VARCHAR2 (150) "
        },
        "ATTRIBUTE13": {
          "type": "VARCHAR2(150)",
          "nullable": true,
          "info": "Attribute fields (flexfields) allow you to add additional information about an object. Data type VARCHAR2 (150) "
        },
        "ATTRIBUTE14": {
          "type": "VARCHAR2(150)",
          "nullable": true,
          "info": "Attribute fields (flexfields) allow you to add additional information about an object. Data type VARCHAR2 (150) "
        },
        "ATTRIBUTE15": {
          "type": "VARCHAR2(150)",
          "nullable": true,
          "info": "Attribute fields (flexfields) allow you to add additional information about an object. Data type VARCHAR2 (150) "
        },
        "ATTRIBUTE16": {
          "type": "VARCHAR2(150)",
          "nullable": true,
          "info": "Attribute fields (flexfields) allow you to add additional information about an object. Data type VARCHAR2 (150) "
        },
        "ATTRIBUTE17": {
          "type": "VARCHAR2(150)",
          "nullable": true,
          "info": "Attribute fields (flexfields) allow you to add additional information about an object. Data type VARCHAR2 (150) "
        },
        "ATTRIBUTE18": {
          "type": "VARCHAR2(150)",
          "nullable": true,
          "info": "Attribute fields (flexfields) allow you to add additional information about an object. Data type VARCHAR2 (150) "
        },
        "ATTRIBUTE19": {
          "type": "VARCHAR2(150)",
          "nullable": true,
          "info": "Attribute fields (flexfields) allow you to add additional information about an object. Data type VARCHAR2 (150) "
        },
        "ATTRIBUTE20": {
          "type": "VARCHAR2(150)",
          "nullable": true,
          "info": "Attribute fields (flexfields) allow you to add additional information about an object. Data type VARCHAR2 (150) "
        },
        "ATTRIBUTE_NUMBER1": {
          "type": "NUMBER()",
          "nullable": true,
          "info": "Attribute fields (flexfields) allow you to add additional information about an object. Data type NUMBER "
        },
        "ATTRIBUTE_NUMBER2": {
          "type": "NUMBER()",
          "nullable": true,
          "info": "Attribute fields (flexfields) allow you to add additional information about an object. Data type NUMBER "
        },
        "ATTRIBUTE_NUMBER3": {
          "type": "NUMBER()",
          "nullable": true,
          "info": "Attribute fields (flexfields) allow you to add additional information about an object. Data type NUMBER "
        },
        "ATTRIBUTE_NUMBER4": {
          "type": "NUMBER()",
          "nullable": true,
          "info": "Attribute fields (flexfields) allow you to add additional information about an object. Data type NUMBER "
        },
        "ATTRIBUTE_NUMBER5": {
          "type": "NUMBER()",
          "nullable": true,
          "info": "Attribute fields (flexfields) allow you to add additional information about an object. Data type NUMBER "
        },
        "ATTRIBUTE_NUMBER6": {
          "type": "NUMBER()",
          "nullable": true,
          "info": "Attribute fields (flexfields) allow you to add additional information about an object. Data type NUMBER "
        },
        "ATTRIBUTE_NUMBER7": {
          "type": "NUMBER()",
          "nullable": true,
          "info": "Attribute fields (flexfields) allow you to add additional information about an object. Data type NUMBER "
        },
        "ATTRIBUTE_NUMBER8": {
          "type": "NUMBER()",
          "nullable": true,
          "info": "Attribute fields (flexfields) allow you to add additional information about an object. Data type NUMBER "
        },
        "ATTRIBUTE_NUMBER9": {
          "type": "NUMBER()",
          "nullable": true,
          "info": "Attribute fields (flexfields) allow you to add additional information about an object. Data type NUMBER "
        },
        "ATTRIBUTE_NUMBER10": {
          "type": "NUMBER()",
          "nullable": true,
          "info": "Attribute fields (flexfields) allow you to add additional information about an object. Data type NUMBER "
        },
        "ATTRIBUTE_DATE1": {
          "type": "DATE",
          "nullable": true,
          "info": "Attribute fields (flexfields) allow you to add additional information about an object. Data type date "
        },
        "ATTRIBUTE_DATE2": {
          "type": "DATE",
          "nullable": true,
          "info": "Attribute fields (flexfields) allow you to add additional information about an object. Data type date "
        },
        "ATTRIBUTE_DATE3": {
          "type": "DATE",
          "nullable": true,
          "info": "Attribute fields (flexfields) allow you to add additional information about an object. Data type date "
        },
        "ATTRIBUTE_DATE4": {
          "type": "DATE",
          "nullable": true,
          "info": "Attribute fields (flexfields) allow you to add additional information about an object. Data type date "
        },
        "ATTRIBUTE_DATE5": {
          "type": "DATE",
          "nullable": true,
          "info": "Attribute fields (flexfields) allow you to add additional information about an object. Data type date "
        },
        "ATTRIBUTE_DATE6": {
          "type": "DATE",
          "nullable": true,
          "info": "Attribute fields (flexfields) allow you to add additional information about an object. Data type date "
        },
        "ATTRIBUTE_DATE7": {
          "type": "DATE",
          "nullable": true,
          "info": "Attribute fields (flexfields) allow you to add additional information about an object. Data type date "
        },
        "ATTRIBUTE_DATE8": {
          "type": "DATE",
          "nullable": true,
          "info": "Attribute fields (flexfields) allow you to add additional information about an object. Data type date "
        },
        "ATTRIBUTE_DATE9": {
          "type": "DATE",
          "nullable": true,
          "info": "Attribute fields (flexfields) allow you to add additional information about an object. Data type date "
        },
        "ATTRIBUTE_DATE10": {
          "type": "DATE",
          "nullable": true,
          "info": "Attribute fields (flexfields) allow you to add additional information about an object. Data type date "
        },
        "IS_EXCLUSIVE_USE": {
          "type": "VARCHAR2(1)",
          "nullable": false,
          "values": [
            "Y",
            "N"
          ],
          "info": "Used to specify if the ship unit is EXCLUSIVE USE. Ship unit is not mixed with anything even if they belong to the same MIXING family if its marked as EXCLUSIVE USE. "
        },
        "PRIORITY": {
          "type": "NUMBER(3)",
          "nullable": true,
          "info": "This column defines the priority associated with a ship unit. "
        },
        "ATTRIBUTE_NUMBER11": {
          "type": "NUMBER()",
          "nullable": true,
          "info": "Attribute fields (flexfields) allow you to add additional information about an object. Data type NUMBER "
        },
        "ATTRIBUTE_NUMBER12": {
          "type": "NUMBER()",
          "nullable": true,
          "info": "Attribute fields (flexfields) allow you to add additional information about an object. Data type NUMBER "
        },
        "ATTRIBUTE_NUMBER13": {
          "type": "NUMBER()",
          "nullable": true,
          "info": "Attribute fields (flexfields) allow you to add additional information about an object. Data type NUMBER "
        },
        "ATTRIBUTE_NUMBER14": {
          "type": "NUMBER()",
          "nullable": true,
          "info": "Attribute fields (flexfields) allow you to add additional information about an object. Data type NUMBER "
        },
        "ATTRIBUTE_NUMBER15": {
          "type": "NUMBER()",
          "nullable": true,
          "info": "Attribute fields (flexfields) allow you to add additional information about an object. Data type NUMBER "
        },
        "ATTRIBUTE_NUMBER16": {
          "type": "NUMBER()",
          "nullable": true,
          "info": "Attribute fields (flexfields) allow you to add additional information about an object. Data type NUMBER "
        },
        "ATTRIBUTE_NUMBER17": {
          "type": "NUMBER()",
          "nullable": true,
          "info": "Attribute fields (flexfields) allow you to add additional information about an object. Data type NUMBER "
        },
        "ATTRIBUTE_NUMBER18": {
          "type": "NUMBER()",
          "nullable": true,
          "info": "Attribute fields (flexfields) allow you to add additional information about an object. Data type NUMBER "
        },
        "ATTRIBUTE_NUMBER19": {
          "type": "NUMBER()",
          "nullable": true,
          "info": "Attribute fields (flexfields) allow you to add additional information about an object. Data type NUMBER "
        },
        "ATTRIBUTE_NUMBER20": {
          "type": "NUMBER()",
          "nullable": true,
          "info": "Attribute fields (flexfields) allow you to add additional information about an object. Data type NUMBER "
        },
        "ATTRIBUTE_DATE11": {
          "type": "DATE",
          "nullable": true,
          "info": "Attribute fields (flexfields) allow you to add additional information about an object. Data type date "
        },
        "ATTRIBUTE_DATE12": {
          "type": "DATE",
          "nullable": true,
          "info": "Attribute fields (flexfields) allow you to add additional information about an object. Data type date "
        },
        "ATTRIBUTE_DATE13": {
          "type": "DATE",
          "nullable": true,
          "info": "Attribute fields (flexfields) allow you to add additional information about an object. Data type date "
        },
        "ATTRIBUTE_DATE14": {
          "type": "DATE",
          "nullable": true,
          "info": "Attribute fields (flexfields) allow you to add additional information about an object. Data type date "
        },
        "ATTRIBUTE_DATE15": {
          "type": "DATE",
          "nullable": true,
          "info": "Attribute fields (flexfields) allow you to add additional information about an object. Data type date "
        },
        "ATTRIBUTE_DATE16": {
          "type": "DATE",
          "nullable": true,
          "info": "Attribute fields (flexfields) allow you to add additional information about an object. Data type date "
        },
        "ATTRIBUTE_DATE17": {
          "type": "DATE",
          "nullable": true,
          "info": "Attribute fields (flexfields) allow you to add additional information about an object. Data type date "
        },
        "ATTRIBUTE_DATE18": {
          "type": "DATE",
          "nullable": true,
          "info": "Attribute fields (flexfields) allow you to add additional information about an object. Data type date "
        },
        "ATTRIBUTE_DATE19": {
          "type": "DATE",
          "nullable": true,
          "info": "Attribute fields (flexfields) allow you to add additional information about an object. Data type date "
        },
        "ATTRIBUTE_DATE20": {
          "type": "DATE",
          "nullable": true,
          "info": "Attribute fields (flexfields) allow you to add additional information about an object. Data type date"
        }
      },
      "fk_tables": [
        "OMR_D",
        "SHIPMENT_STOP_DEBRIEF",
        "SHIP_UNIT_CHILD",
        "SHIP_UNIT_EQUIP_REF_UNIT_JOIN",
        "SHIP_UNIT_LINE",
        "SHIP_UNIT_LOADING_SPLIT",
        "SHIP_UNIT_REFNUM",
        "SHIP_UNIT_REMARK",
        "SHIP_UNIT_SEAL",
        "SHIP_UNIT_SPECIAL_SERVICE",
        "SHIP_UNIT_TEXT",
        "S_SHIP_UNIT"
      ]
    }
  }
};
