// BILLABLE_TRANSACTION.js

window.BILLABLE_TRANSACTION = {
  "tables": {
    "BILLABLE_TRANSACTION": {
      "columns": {
        "SEQUENCE_NO": {
          "type": "VARCHAR2(50)",
          "nullable": false,
          "key_value": true,
          "info": "A sequence number for data integrity. Generated by BNG to allow for transactional rollback."
},
        "NOTIFY_SUBJECT_GID": {
          "type": "VARCHAR2(101)",
          "nullable": false,
          "foreign_key": "NOTIFY_SUBJECT",
          "info": "This doubles as transaction type."
},
        "OBJECT_ID": {
          "type": "VARCHAR2(101)",
          "nullable": true,
          "info": "Object GID for which the lifetime event was generated"
},
        "OBJECT_TYPE": {
          "type": "VARCHAR2(101)",
          "nullable": true
},
        "NOTIFY_DOMAIN_NAME": {
          "type": "VARCHAR2(50)",
          "nullable": false
},
        "TRANSACTION_TIME": {
          "type": "DATE",
          "nullable": false,
          "info": "Local server time when the transaction is recorded"
},
        "MESSAGE_DIGEST": {
          "type": "VARCHAR2(30)",
          "nullable": false,
          "info": "A message digest of the rest of the fields."
},
        "DOMAIN_NAME": {
          "type": "VARCHAR2(50)",
          "nullable": false
},
        "INSERT_USER": {
          "type": "VARCHAR2(128)",
          "nullable": false
},
        "INSERT_DATE": {
          "type": "DATE",
          "nullable": false
},
        "UPDATE_USER": {
          "type": "VARCHAR2(128)",
          "nullable": true
},
        "UPDATE_DATE": {
          "type": "DATE",
          "nullable": true
}
      },
      "fk_tables": []
    }
  }
};