// BULK_TRAILER_BUILD.js

window.BULK_TRAILER_BUILD = {
  "tables": {
    "BULK_TRAILER_BUILD": {
      "description": "Provides information about what shipments were selected and what shipment groups were created during a given run of bulk trailer build.",
      "columns": {
        "BULK_TRAILER_BUILD_GID": {
          "type": "VARCHAR2(101)",
          "nullable": false,
          "key_value": true,
          "info": "Unique identifier for the bulk trailer build process."
},
        "BULK_TRAILER_BUILD_XID": {
          "type": "VARCHAR2(50)",
          "nullable": false,
          "info": "External identifier for the bulk trailer build process."
},
        "QUERY_NAME": {
          "type": "VARCHAR2(120)",
          "nullable": true,
          "info": "Bulk trailer build input parameter."
},
        "START_TIME": {
          "type": "DATE",
          "nullable": true,
          "info": "Start time of the bulk trailer build."
},
        "END_TIME": {
          "type": "DATE",
          "nullable": true,
          "info": "End time of the bulk trailer build."
},
        "NUM_SHIPMENTS_SELECTED": {
          "type": "NUMBER(10)",
          "nullable": false,
          "info": "Number of shipments selected for the bulk trailer build."
},
        "NUM_SHIPMENTS_BUILT_TO_GROUPS": {
          "type": "NUMBER(10)",
          "nullable": false,
          "info": "Number of shipments successfully built into shipment groups by the bulk trailer build."
},
        "NUM_SHIPMENTS_NOT_IN_GROUPS": {
          "type": "NUMBER(10)",
          "nullable": false,
          "info": "Number of shipments not built into any of the shipment groups by the bulk trailer build."
},
        "NUM_SHIPMENT_GROUPS_BUILT": {
          "type": "NUMBER(10)",
          "nullable": false,
          "info": "Number of shipment groups generated by the bulk trailer build process."
},
        "LOG_PROCESS_ID": {
          "type": "NUMBER",
          "nullable": true,
          "info": "The log id for the bulk trailer build process."
},
        "APP_MACHINE_GID": {
          "type": "VARCHAR2(101)",
          "nullable": true,
          "foreign_key": "APP_MACHINE",
          "info": "Application machine id the process is running on, in order to get the log from the correct machine."
},
        "DOMAIN_NAME": {
          "type": "VARCHAR2(50)",
          "nullable": false
},
        "INSERT_USER": {
          "type": "VARCHAR2(128)",
          "nullable": false
},
        "INSERT_DATE": {
          "type": "DATE",
          "nullable": false
},
        "UPDATE_USER": {
          "type": "VARCHAR2(128)",
          "nullable": true
},
        "UPDATE_DATE": {
          "type": "DATE",
          "nullable": true
}
      },
      "fk_tables": []
    }
  }
};