// DOCUMENT.js

window.DOCUMENT = {
  "tables": {
    "DOCUMENT": {
      "columns": {
        "DOCUMENT_GID": {
          "type": "VARCHAR2(101)",
          "nullable": false,
          "key_value": true
},
        "DOCUMENT_XID": {
          "type": "VARCHAR2(80)",
          "nullable": false
},
        "DOCUMENT_DEF_GID": {
          "type": "VARCHAR2(101)",
          "nullable": true,
          "foreign_key": "DOCUMENT_DEF"
},
        "DOCUMENT_URL": {
          "type": "VARCHAR2(1000)",
          "nullable": true
},
        "DOCUMENT_TYPE": {
          "type": "VARCHAR2(10)",
          "nullable": true,
          "values": [
                    "URL",
                    "SECURE URL",
                    "CLOB",
                    "BLOB",
                    "CMS",
                    "CMS URL"
          ]
},
        "DOCUMENT_MIME_TYPE": {
          "type": "VARCHAR2(500)",
          "nullable": true
},
        "DOCUMENT_FILENAME": {
          "type": "VARCHAR2(1000)",
          "nullable": true
},
        "OWNER_DATA_QUERY_TYPE_GID": {
          "type": "VARCHAR2(101)",
          "nullable": true,
          "foreign_key": "DATA_QUERY_TYPE"
},
        "OWNER_OBJECT_GID": {
          "type": "VARCHAR2(101)",
          "nullable": true
},
        "INDICATOR": {
          "type": "VARCHAR2(1)",
          "nullable": true
},
        "MARKED_FOR_PURGE": {
          "type": "VARCHAR2(1)",
          "nullable": true,
          "values": [
                    "Y",
                    "N"
          ],
          "info": "A boolean field. When it is set to 'Y', this row and its child data will be purged."
},
        "DOMAIN_NAME": {
          "type": "VARCHAR2(50)",
          "nullable": false
},
        "INSERT_USER": {
          "type": "VARCHAR2(128)",
          "nullable": false
},
        "INSERT_DATE": {
          "type": "DATE",
          "nullable": false
},
        "UPDATE_USER": {
          "type": "VARCHAR2(128)",
          "nullable": true
},
        "UPDATE_DATE": {
          "type": "DATE",
          "nullable": true
},
        "REPORT_GID": {
          "type": "VARCHAR2(101)",
          "nullable": true,
          "foreign_key": "REPORT",
          "info": "The report associated with the document attachment, if content was generated by the report subsystem."
},
        "GENERATED_AT": {
          "type": "DATE",
          "nullable": true,
          "info": "If preparation, date/time content was last generated"
},
        "UPLOADED_AT": {
          "type": "DATE",
          "nullable": true,
          "info": "If attachment, date/time content was last updated"
},
        "DOCUMENT_TRACKING_NUM": {
          "type": "VARCHAR2(50)",
          "nullable": true
},
        "DOCUMENT_CMS_ID": {
          "type": "VARCHAR2(500)",
          "nullable": true,
          "info": "A GUID to associate the document with content stored on its remote CMS. Valid when document_type=CMS."
},
        "CONTENT_MANAGEMENT_SYSTEM_GID": {
          "type": "VARCHAR2(101)",
          "nullable": true,
          "foreign_key": "CONTENT_MANAGEMENT_SYSTEM"
},
        "USED_AS": {
          "type": "VARCHAR2(1)",
          "nullable": true,
          "values": [
                    "C",
                    "I",
                    "L",
                    "T"
          ],
          "info": "Represents the classification of a document.(C/I/L/T)"
},
        "RELATED_DOCUMENT_GID": {
          "type": "VARCHAR2(101)",
          "nullable": true,
          "foreign_key": "DOCUMENT",
          "info": "Represents the related document for consolidated/linked documents."
},
        "EFFECTIVE_DATE": {
          "type": "DATE",
          "nullable": true,
          "info": "represents effective date for a document"
},
        "EXPIRATION_DATE": {
          "type": "DATE",
          "nullable": true,
          "info": "Represents expiration date for a document."
},
        "USER_DEFINED1_ICON_GID": {
          "type": "VARCHAR2(101)",
          "nullable": true,
          "foreign_key": "ICON"
},
        "USER_DEFINED2_ICON_GID": {
          "type": "VARCHAR2(101)",
          "nullable": true,
          "foreign_key": "ICON"
},
        "USER_DEFINED3_ICON_GID": {
          "type": "VARCHAR2(101)",
          "nullable": true,
          "foreign_key": "ICON"
},
        "USER_DEFINED4_ICON_GID": {
          "type": "VARCHAR2(101)",
          "nullable": true,
          "foreign_key": "ICON"
},
        "USER_DEFINED5_ICON_GID": {
          "type": "VARCHAR2(101)",
          "nullable": true,
          "foreign_key": "ICON"
}
      },
      "fk_tables": [
        "DOCUMENT",
        "DOCUMENT_CMS_PARAM",
        "DOCUMENT_CONTEXT",
        "DOCUMENT_DEF_TEMPLATE_MAP",
        "DOCUMENT_DOC_CONTENT_JOIN",
        "DOCUMENT_STATUS",
        "GTM_CAMPAIGN_REQD_DOC",
        "GTM_CA_LINE_REQD_DOC",
        "GTM_TRANS_REQD_DOC",
        "ITEM_QF_REQD_DOC",
        "ITEM_REQDOC_DOC",
        "ITEM_REQDOC_DOC_REVIEW",
        "SHIPMENT_REQDOC_DOC",
        "SS_DOCUMENT",
        "WEB_SERVICE"
]
    }
  }
};