// GTM_TRANSACTION_LINE_NOTE.js

window.GTM_TRANSACTION_LINE_NOTE = {
  "tables": {
    "GTM_TRANSACTION_LINE_NOTE": {
      "description": "This table is intended to hold the notes that gives information about the result of the actions/events performed on a transaction line.",
      "columns": {
        "DOMAIN_NAME": {
          "type": "VARCHAR2(50)",
          "nullable": false,
          "info": "Database domain where this data is stored."
},
        "INSERT_USER": {
          "type": "VARCHAR2(128)",
          "nullable": false,
          "info": "The user ID of the data insert user."
},
        "INSERT_DATE": {
          "type": "DATE",
          "nullable": false,
          "info": "Date and time of data insert."
},
        "UPDATE_USER": {
          "type": "VARCHAR2(128)",
          "nullable": true,
          "info": "The user ID of the data update user."
},
        "UPDATE_DATE": {
          "type": "DATE",
          "nullable": true,
          "info": "Date and time of the most recent data update."
},
        "GTM_TRANSACTION_LINE_GID": {
          "type": "VARCHAR2(201)",
          "nullable": false,
          "key_value": true,
          "foreign_key": "GTM_TRANSACTION_LINE",
          "info": "The GID for the GTM trade transaction line."
},
        "NOTE_SEQUENCE_NO": {
          "type": "NUMBER",
          "nullable": false,
          "key_value": true,
          "info": "Sequence number of notes."
},
        "TIMESTAMP": {
          "type": "DATE",
          "nullable": false,
          "info": "Timestamp of the event that is noted."
},
        "SUMMARY": {
          "type": "VARCHAR2(500)",
          "nullable": false,
          "info": "High level description about the event."
},
        "NOTE": {
          "type": "VARCHAR2(4000)",
          "nullable": true,
          "info": "Detailed description about the event."
},
        "ENTERED_BY": {
          "type": "VARCHAR2(128)",
          "nullable": true,
          "info": "The action name or the manual intervention that resulted in this note"
},
        "IS_SYSTEM_GENERATED": {
          "type": "VARCHAR2(1)",
          "nullable": false,
          "values": [
                    "Y",
                    "N"
          ],
          "info": "Says if the note is generated by the system or manually added by the user."
}
      },
      "fk_tables": []
    }
  }
};