// LOGISTICS_GUIDE.js

window.LOGISTICS_GUIDE = {
  "tables": {
    "LOGISTICS_GUIDE": {
      "description": "This is the top level output table for the logistics guide",
      "columns": {
        "LOGISTICS_GUIDE_GID": {
          "type": "VARCHAR2(101)",
          "nullable": false,
          "key_value": true,
          "info": "Usually generated by BNG from DOMAIN.LOGISTICS_GUIDE_TEMPLATE_XID"
},
        "LOGISTICS_GUIDE_XID": {
          "type": "VARCHAR2(50)",
          "nullable": false,
          "info": "Usually generated by BNG from LOGISTICS_GUIDE_TEMPLATE_XID"
},
        "LOGISTICS_GUIDE_TEMPLATE_GID": {
          "type": "VARCHAR2(101)",
          "nullable": true,
          "foreign_key": "LOGISTICS_GUIDE_TEMPLATE",
          "info": "Template from which this guide was generated"
},
        "LOGISTICS_GUIDE_START_TIME": {
          "type": "DATE",
          "nullable": false,
          "info": "Time when the run was started"
},
        "LOGISTICS_GUIDE_END_TIME": {
          "type": "DATE",
          "nullable": true,
          "info": "Time when the run finished"
},
        "PERSPECTIVE": {
          "type": "VARCHAR2(1)",
          "nullable": false,
          "values": [
                    "B",
                    "S"
          ]
},
        "DOMAIN_NAME": {
          "type": "VARCHAR2(50)",
          "nullable": false
},
        "INSERT_USER": {
          "type": "VARCHAR2(128)",
          "nullable": false
},
        "INSERT_DATE": {
          "type": "DATE",
          "nullable": false
},
        "UPDATE_USER": {
          "type": "VARCHAR2(128)",
          "nullable": true
},
        "UPDATE_DATE": {
          "type": "DATE",
          "nullable": true
},
        "COST_PER_UOM_CODE": {
          "type": "VARCHAR2(64)",
          "nullable": true
}
      },
      "fk_tables": [
        "LG_EXCHANGE_RATE_JOIN",
        "LOGISTICS_GUIDE_AGGREGATE_DATA",
        "LOGISTICS_GUIDE_DETAIL"
]
    }
  }
};